version: "3"

volumes:
  jellyfin-config:
  jellyfin-cache:

services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    user: "1000:1000"
    network_mode: host
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /path/to/media1:/media1
      - /path/to/media2:/media2:ro
    restart: always
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
