version: "3"

volumes:
  jellyfin-config:
  jellyfin-cache:

services:

  jellyfin:
    image: docker.io/liukunup/jellyfin:10.10.3
    container_name: jellyfin
    hostname: jellyfin
    user: uid:gid
    network_mode: host
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /path/to/certs:/certs:ro # Optional (see https://jellyfin.org/docs/general/networking/#self-signed-certificate)
      - /path/to/fonts:/usr/local/share/fonts/custom
      - /path/to/media1:/media1
      - /path/to/media2:/media2:ro
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.homelab.lan
