---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  rules:
  - host: jellyfin.homelab.lan
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jellyfin
            port:
              number: 8096
# Add HTTPS configuration
  tls:
  - hosts:
    - jellyfin.homelab.lan
    secretName: jellyfin-tls